[package]
name = "asky"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Libray to create good looking prompts in the terminal"
categories = ["command-line-interface", "command-line-utilities"]
keywords = ["ask", "cli", "prompt", "question", "readline"]
repository = "https://github.com/axelvc/asky/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
crossterm = "0.26.0"
