[package]
name = "asky"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Libray to create good looking prompts in the terminal"
categories = ["command-line-interface", "command-line-utilities"]
keywords = ["ask", "cli", "prompt", "question", "readline"]
repository = "https://github.com/axelvc/asky/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10.1", default-features = false, optional = true, features = [ "bevy_render", "bevy_ui", "bevy_text",    "bevy_core_pipeline", "bevy_asset", "bevy_sprite", "bevy_winit" ] }
# colored = { version = "2.0.0", default-features = false }
colored = { path = "../colored", default-features = false }
crossterm = { version = "0.26.0", optional = true }

[features]
default = ["terminal"]
terminal = ["dep:crossterm", "colored/tty", "colored/color"]
bevy = ["dep:bevy"]

[[example]]
name = "bevy"
path = "examples/bevy.rs"
required-features = [ "bevy" ]

[[example]]
name = "bevy-confirm"
path = "examples/bevy/confirm.rs"
required-features = [ "bevy" ]
